name: TEST

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          sudo apt install g++
      - name: build
        run: |
          make
      - name: run
        run: |
          cd prime-search\
          make test
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          sudo apt install g++
      - name: build
        run: |
          make
      - name: run
        run: |
          cd benchmark\
          make run
